<a href="https://colab.research.google.com/github/bhavikakalra085/102316086_UCS420/blob/main/assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

In [2]:
arr=np.array([1,2,3,4,5])

a) Addition of 2 in all the element

In [3]:
add=arr+2

In [4]:
add

array([3, 4, 5, 6, 7])

b) Multiply 3 with all the elements

In [11]:
multiply=arr*3


In [12]:
multiply

array([ 3,  6,  9, 12, 15])

c) Divide every element by 2

In [13]:
div=arr/2

In [14]:
div

array([0.5, 1. , 1.5, 2. , 2.5])

Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [21]:
 arrey=np.array([1, 2, 3, 6, 4, 5])

In [26]:
np.flip(arrey,axis=0)

array([5, 4, 6, 3, 2, 1])

b) Find the most frequent value and their indice(s) in the following arrays:

In [29]:
x=np.array([1,2,3,4,5,1,2,1,1,1])

In [30]:
print("maximum element in x array : ",np.bincount(x).argmax())

maximum element in x array :  1


ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [31]:
y=np.array([1,1,1,2,3,4,2,4,3,3])
print("maximum element in y array : ",np.bincount(y).argmax())

maximum element in y array :  1


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

In [32]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

a) Access 1st row, 2nd column

In [33]:
arr[0][1]

20

b) Access 3rd row, 1st column

In [34]:
arr[2][0]

70

Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [35]:
ab=np.array(np.linspace(10,100,num=25))

In [36]:
ab

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [37]:
print("dimension of array :",ab.ndim)

dimension of array : 1


In [39]:
print("shape of array:",ab.shape)

shape of array: (25,)


In [41]:
print("total number of elements :",np.size(ab))

total number of elements : 25


In [43]:
print("data type of array elements :",ab.dtype)

data type of array elements : float64


In [44]:
print("total bytes of array :",ab.nbytes)

total bytes of array : 200


In [45]:
ab.reshape(25,1)

array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

In [46]:
print("before transpose :")
print(ab.T)
print("transposed array :")
print(ab.T)

before transpose :
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
transposed array :
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_shraddha>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_bhavika>. Resize the array to two rows and three
columns and name it as resized_ ucs420_bhavika>

In [48]:
ucs420_bhavika=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
ucs420_bhavika

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 15, 20, 35]])

In [49]:
mean=np.mean(ucs420_bhavika)
print("mean of array :",mean)

mean of array : 43.333333333333336


In [50]:
median=np.median(ucs420_bhavika)
print("median of array :",median)

median of array : 37.5


In [51]:
unique_elements=np.unique(ucs420_bhavika)
print(unique_elements)

[10 15 20 30 35 40 50 60 70 80 90]


In [52]:
maxArr=ucs420_bhavika.max()
print("max. element in array :",maxArr)

max. element in array : 90


In [53]:
minArr=ucs420_bhavika.min()
print("min. element in array :",minArr)

min. element in array : 10


In [54]:
reshaped_ucs420_bhavika=ucs420_bhavika.reshape(4,3)
print(reshaped_ucs420_bhavika)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [55]:
resized_ucs420_bhavika=np.resize(ucs420_bhavika,(2,3))
resized_ucs420_bhavika

array([[10, 20, 30],
       [40, 50, 60]])